### ISSUE TITLE
Further check possible when reading values; avoids bad data

### ISSUE THREAD

**Issue by c2bdii** [paulvha/sps30#19]
I have an SPS30 readout by an ESP8266-NodeMCU, powered by the 5 V pin and using SoftSerial UART with 3.3 V communications.
It has frequent read errors (one per 100 or so), usually caught by the CRC check. But I guess with an 8bit CRC check, once in 256 errors you happen to get the same code by chance, allowing bad data through. Most such events have a few data words missing, and crazy values like billions or negative. So the payload is 0x28, but the actual length value is less than 46 (typically 43). This is easy to detect, just after the redundancy check. When I put this in, it cleared up all the bad data (well, for 24 hours running, reading continuously).

**Comment by paulvha** [comment]
hi,
Thanks for your feedback.
The issue is NOT SPS30 nor CRC failing. It works in many places without any problems for a long time. The problem is related to SoftSerial and the connection speed. SoftSerial is highly dependent on-time interrupt handling. As soon as the RX line detects a rising edge, which is an indication of a start, it will raise an interrupt.  If that interrupt is not handled on-time, e.g the processor is busy already handling another interrupt, incoming bits will be missed from incoming characters on the RX line. Next to that, I have only seen SoftSerial work stable up to 56K (on a Mega2560). The SPS30 only works on 115K.  Of course, you can as you did, increase checks to remove packets in error, but that getting a good packet is still "hope and pray". Especially if the processor load is increased e.g. by adding a WIFI connection.  As I want a stable solution and therefore on an ESP8266 I only use I2C.

regards,
Paul
